config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root :to => redirect('/color_palettes')
  get    '/color_palettes'           => 'color_palettes#index'

  get    '/color_palettes/new'       => 'color_palettes#new', as: 'new_color_palette'
  get    '/color_palettes/:id/edit'  => 'color_palettes#edit', as: 'edit_color_palette'
  get    '/color_palettes/:id'       => 'color_palettes#show', as: 'color_palette'

  post   '/color_palettes'           => 'color_palettes#create'
  patch  '/color_palettes/:id'       => 'color_palettes#update'
  put    '/color_palettes/:id'       => 'color_palettes#update'

  delete '/color_palettes/:id'       => 'color_palettes#destroy'

  get    '/ideas'           => 'ideas#index'

  get    '/ideas/new'       => 'ideas#new', as: 'new_idea'
  get    '/ideas/:id/edit'  => 'ideas#edit', as: 'edit_idea'
  get    '/ideas/:id'       => 'ideas#show', as: 'idea'

  post   '/ideas'           => 'ideas#create'
  patch  '/ideas/:id'       => 'ideas#update'
  put    '/ideas/:id'       => 'ideas#update'

  delete '/ideas/:id'       => 'ideas#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color_palette.rb
class ColorPalette < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/color_palettes_controller.rb
class ColorPalettesController < ApplicationController
  def index
    @color_palettes = ColorPalette.all
    render 'index'
  end
  def show
    @color_palette = ColorPalette.find(params[:id])
    render 'show'
  end
  def new
    @color_palette = ColorPalette.new
    render 'new'
  end
  def edit
    @color_palette = ColorPalette.find(params[:id])
    render 'edit'
  end
  def create
    @color_palette = ColorPalette.new(color_palette_params)
    if @color_palette.save
      redirect_to @color_palette, notice: 'Color palette was successfully created.'
    else
      render action: 'new'
    end
  end
  def update
    @color_palette = ColorPalette.find(params[:id])
    if @color_palette.update(color_palette_params)
      redirect_to @color_palette, notice: 'Color palette was successfully updated.'
    else
      render action: 'edit'
    end
  end
  def destroy
    @color_palette = ColorPalette.find(params[:id])
    @color_palette.destroy
    redirect_to color_palettes_url, notice: 'Color palette was successfully destroyed.'
  end
  private
  # Only allow a trusted parameter "white list" through.
  def color_palette_params
    params.require(:color_palette).permit(:name, :description, :picture)
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
    render 'index'
  end
  def show
    @idea = Idea.find(params[:id])
    render 'show'
  end
  def new
    @idea = Idea.new
    render 'new'
  end
  def edit
    @idea = Idea.find(params[:id])
    render 'edit'
  end
  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to @idea, notice: 'Idea was successfully created.'
    else
      render action: 'new'
    end
  end
  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to @idea, notice: 'Idea was successfully updated.'
    else
      render action: 'edit'
    end
  end
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_url, notice: 'Idea was successfully destroyed.'
  end
  private
  # Only allow a trusted parameter "white list" through.
  def idea_params
    params.require(:idea).permit(:name, :description, :picture)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/color_palettes/_form.html.erb
<%= form_with(model: color_palette, local: true, multipart: true) do |form| %>
  <% if color_palette.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(color_palette.errors.count, "error") %> prohibited this color_palette from being saved:</h2>

      <ul>
      <% color_palette.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :color_palette_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :color_palette_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :color_palette_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/color_palettes/edit.html.erb
<h1>Editing Color Palette</h1>

<%= render 'form', color_palette: @color_palette %>

<%= link_to 'Show', @color_palette %> |
<%= link_to 'Back', color_palettes_path %>

app/views/color_palettes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Color Palettes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @color_palettes.each do |color_palette| %>
      <tr>
        <td><%= color_palette.name %></td>
        <td><%= color_palette.description %></td>
        <td><%= image_tag(color_palette.picture_url, :width => 100) if color_palette.picture.present? %></td>
        <td><%= link_to 'Show', color_palette %></td>
        <td><%= link_to 'Edit', edit_color_palette_path(color_palette) %></td>
        <td><%= link_to 'Destroy', color_palette, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Color Palette', new_color_palette_path %>

app/views/color_palettes/new.html.erb
<h1>New Color Palette</h1>

<%= render 'form', color_palette: @color_palette %>

<%= link_to 'Back', color_palettes_path %>

app/views/color_palettes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @color_palette.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @color_palette.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@color_palette.picture_url) if @color_palette.picture.present? %>
</p>

<%= link_to 'Edit', edit_color_palette_path(@color_palette) %> |
<%= link_to 'Back', color_palettes_path %>

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :idea_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :idea_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :idea_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgirls</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
  <div class='container'>
    <div class='navbar-header'>
      <a class='navbar-brand' href='/'>Palette</a>
    </div>
    <ul class='nav navbar-nav'>
      <li>
        <a href='/color_palettes/'>Ideas</a>
      </li>
    </ul>
  </div>
</nav>
    <div class='container'>
  <%= yield %>
</div>
<footer>
  <div class='container'>
    Rails Girls 2016
  </div>
</footer>
  </body>
</html>

app/views/pages/info.html.erb
<h1>Kasia Pajak</h1>
<a href="https://www.facebook.com/kasia.pajak.14">Visit my FB</a>